# Generated by Django 4.2.23 on 2025-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employeecalendar_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True),
        ),
    ]
