# Generated by Django 4.2.23 on 2025-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slot_interval',
            field=models.PositiveIntegerField(default=30, help_text='Interval between available start times (in minutes).'),
        ),
    ]
