# Generated by Django 4.2.23 on 2025-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_slot_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allowed_start_times',
            field=models.CharField(default='09:00,11:30,14:00', help_text="Comma-separated start times (e.g., '09:00,11:30,14:00')", max_length=200),
        ),
    ]
