# Generated by Django 4.2.23 on 2025-08-07 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_remove_service_price_serviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pet_approved', 'Pet Approved'), ('pet_rejected', 'Pet Rejected'), ('appointment_approved', 'Appointment Approved'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_reassigned', 'Appointment Reassigned'), ('appointment_cancelled', 'Appointment Cancelled'), ('login_attempt', 'Login Attempt')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by the action (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
    ]
