# Generated by Django 4.2.23 on 2025-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('client', 'Client'), ('employee', 'Employee'), ('manager', 'Manager')], max_length=10),
        ),
    ]
