# Generated by Django 4.2.23 on 2025-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_created_at_service_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this appointment has been edited by the client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final calculated price for this appointment', max_digits=8, null=True),
        ),
    ]
