# Generated by Django 4.2.23 on 2025-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointment_edit_count_appointment_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('pet_approved', 'Pet Approved'), ('pet_rejected', 'Pet Rejected'), ('appointment_approved', 'Appointment Approved'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_reassigned', 'Appointment Reassigned'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_edited', 'Appointment Edited'), ('login_attempt', 'Login Attempt')], max_length=50),
        ),
    ]
