# Generated by Django 4.2.23 on 2025-08-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_rejected_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
