# Generated by Django 4.2.23 on 2025-08-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_auditlog'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_auditlog CASCADE;",
            reverse_sql="-- No reverse operation for manual table cleanup"
        ),
    ]
